name: My first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v6

            # Running multiple lines at once   
            - name: Welcome 
              run: |
                echo "this is my first workflows"
                ls -ltr
                cat README.md



            # - name: List the files
            #   run: ls
            
            # - name: Read file
            #   run: cat README.md

